const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..", "..");
const packageJson = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
const version = packageJson.version;
const releaseRoot = path.join(root, "dist", "releases", `magnexis-agent-studio-${version}`);
const previewRoot = path.join(root, "workspaces", "runtime", "previews");
const docsRoot = path.join(root, "docs");
const screenshotsRoot = path.join(root, "screenshots");
const vsixName = `magnexis-agent-studio-${version}.vsix`;
const vsixPath = path.join(root, vsixName);

function ensureDir(directory) {
  fs.mkdirSync(directory, { recursive: true });
}

function copyFileIfPresent(sourcePath, targetPath) {
  if (!fs.existsSync(sourcePath)) return false;
  ensureDir(path.dirname(targetPath));
  fs.copyFileSync(sourcePath, targetPath);
  return true;
}

function copyDirectory(sourceDir, targetDir, filter) {
  if (!fs.existsSync(sourceDir)) return;
  ensureDir(targetDir);
  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const sourcePath = path.join(sourceDir, entry.name);
    const targetPath = path.join(targetDir, entry.name);
    if (filter && !filter(sourcePath, entry)) continue;
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, targetPath, filter);
    } else {
      ensureDir(path.dirname(targetPath));
      fs.copyFileSync(sourcePath, targetPath);
    }
  }
}

fs.rmSync(releaseRoot, { recursive: true, force: true });
ensureDir(releaseRoot);

const copied = {
  vsix: copyFileIfPresent(vsixPath, path.join(releaseRoot, vsixName)),
  readme: copyFileIfPresent(path.join(root, "README.md"), path.join(releaseRoot, "README.md")),
  license: copyFileIfPresent(path.join(root, "LICENSE"), path.join(releaseRoot, "LICENSE")),
  contributing: copyFileIfPresent(path.join(root, "CONTRIBUTING.md"), path.join(releaseRoot, "CONTRIBUTING.md")),
  security: copyFileIfPresent(path.join(root, "SECURITY.md"), path.join(releaseRoot, "SECURITY.md"))
};

copyDirectory(docsRoot, path.join(releaseRoot, "docs"), (_, entry) => entry.isDirectory() || entry.name.endsWith(".md"));
copyDirectory(previewRoot, path.join(releaseRoot, "previews"), (_, entry) => entry.isDirectory() || entry.name.endsWith(".html"));
copyDirectory(path.join(root, "media"), path.join(releaseRoot, "media"), (_, entry) => {
  return entry.isDirectory() || /\.(png|svg|css|js)$/i.test(entry.name);
});
copyDirectory(screenshotsRoot, path.join(releaseRoot, "screenshots"), (_, entry) => {
  return entry.isDirectory() || /\.(png|jpg|jpeg|webp)$/i.test(entry.name);
});

const manifest = {
  product: packageJson.name,
  displayName: packageJson.displayName,
  version,
  generatedAt: new Date().toISOString(),
  releaseDirectory: path.relative(root, releaseRoot),
  artifacts: {
    vsix: copied.vsix ? vsixName : null,
    previews: fs.existsSync(previewRoot),
    screenshots: fs.existsSync(screenshotsRoot),
    docs: fs.existsSync(docsRoot)
  },
  notes: [
    "Desktop native installers are not generated by this repository yet.",
    "VS Code Marketplace publication, GitHub Releases, and desktop distribution still require authenticated publishing credentials.",
    "Use `npm run preview:desktop`, `npm run preview:extension`, and `npm run preview:web` to validate the packaged previews before publishing."
  ]
};

fs.writeFileSync(path.join(releaseRoot, "release-manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

console.log(releaseRoot);
